"""
generate_tables.py
"""

import json
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

ROOT    = os.path.join(os.path.dirname(__file__), "..")
RESULTS = os.path.join(ROOT, "results")
FIGS    = os.path.join(ROOT, "figures")
TABLES  = os.path.join(ROOT, "results")  
os.makedirs(FIGS, exist_ok=True)

plt.rcParams.update({
    "font.family": "serif", "font.size": 11,
    "axes.spines.top": False, "axes.spines.right": False,
    "lines.linewidth": 2.0, "figure.dpi": 150,
})

BLUE   = "#2166AC"; RED    = "#D6604D"; GREEN  = "#4DAC26"
ORANGE = "#F4A582"; PURPLE = "#762A83"; TEAL   = "#1B9E77"

MODEL_LABELS = {"phi35": "Phi-3.5-mini (3.8B)", "qwen3b": "Qwen2.5-3B",
                "qwen_1b5": "Qwen2.5-1.5B", "qwen_3b": "Qwen2.5-3B"}
LEVEL_COLORS = {"Level_1": BLUE, "Level_3": ORANGE, "Level_5": RED}
LEVEL_LABELS = {"Level_1": "L1 (easy)", "Level_3": "L3 (med)", "Level_5": "L5 (hard)"}
PREC_COLORS  = {"fp16": BLUE, "bf16": GREEN, "int8": ORANGE, "int4": RED}


def load(name):
    path = os.path.join(RESULTS, name)
    with open(path) as f:
        return json.load(f)


# =============================================================================
# Exp A — accuracy vs. budget (P1 test)
# =============================================================================
def process_expA():
    data = load("multimodel_results_expA.json")
    models_raw = data.get("models", {})

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    fig.suptitle("Exp A: Accuracy vs. Budget by Difficulty\n"
                 "(Phi-3.5-mini & Qwen2.5-3B, MATH-500)", fontsize=12)

    model_order = [("phi35", axes[0]), ("qwen3b", axes[1])]
    table_rows  = []

    for (mkey, ax) in model_order:
        mdata = models_raw.get(mkey, {})
        if not mdata:
            ax.set_visible(False)
            continue
        label = MODEL_LABELS.get(mkey, mkey)
        ax.set_title(label, fontsize=11, fontweight="bold")

        for lv, col in LEVEL_COLORS.items():
            series = mdata.get(lv, [])
            if not series:
                continue
            budgets = [pt["budget"] for pt in series]
            accs    = [pt["accuracy"] * 100 for pt in series]
            ax.plot(budgets, accs, color=col, lw=2,
                    marker="o", ms=5, label=LEVEL_LABELS[lv])
            # collect for table
            for b, a in zip(budgets, accs):
                table_rows.append((mkey, lv, b, a))

        ax.set_xlabel("Budget T (tokens)", fontsize=10)
        ax.set_ylabel("Accuracy (%)", fontsize=10)
        ax.set_xscale("log")
        ax.legend(fontsize=9)
        ax.set_ylim(0, 105)

    fig.tight_layout()
    out = os.path.join(FIGS, "fig_expA_accuracy.png")
    fig.savefig(out, bbox_inches="tight", dpi=200)
    plt.close(fig)
    print(f"  saved → {out}")

    # P1 summary from stored fits
    p1 = data.get("P1_per_model", {})
    print("\n  Exp A — P1 summary (stored fits):")
    for m, lv_dict in p1.items():
        print(f"    {m}: {lv_dict}")

    # Write LaTeX table snippet
    tex = (
        "% Auto-generated by generate_tables.py from results/multimodel_results_expA.json\n"
        "\\begin{table}[t]\n"
        "\\centering\\small\n"
        "\\caption{Exp A: Accuracy (\\%) vs.\\ budget by model and difficulty level "
        "(MATH-500, 8 problems per level).}\n"
        "\\label{tab:expA_accuracy}\n"
        "\\begin{tabular}{llrrrrrrr}\n"
        "\\toprule\n"
        "Model & Level & \\multicolumn{7}{c}{Budget T} \\\\\n"
        "\\cmidrule{3-9}\n"
        " & & 150 & 300 & 600 & 1200 & 2400 & 4800 & 9600 \\\\\n"
        "\\midrule\n"
    )
    for mkey, ax in model_order:
        mdata = models_raw.get(mkey, {})
        for lv in ["Level_1", "Level_3", "Level_5"]:
            series = mdata.get(lv, [])
            acc_by_budget = {pt["budget"]: pt["accuracy"] * 100 for pt in series}
            cells = " & ".join(
                f"{acc_by_budget.get(b, float('nan')):.0f}"
                if not np.isnan(acc_by_budget.get(b, float("nan"))) else "--"
                for b in [150, 300, 600, 1200, 2400, 4800, 9600]
            )
            mlabel = MODEL_LABELS.get(mkey, mkey).split(" ")[0]
            tex += f"{mlabel} & {LEVEL_LABELS[lv]} & {cells} \\\\\n"
        tex += "\\midrule\n"
    tex += "\\bottomrule\n\\end{tabular}\n\\end{table}\n"

    with open(os.path.join(TABLES, "tab_expA_accuracy.tex"), "w") as f:
        f.write(tex)
    print("  saved → results/tab_expA_accuracy.tex")
    return table_rows


# =============================================================================
# Exp B — P6: T* vs. model size
# =============================================================================
def process_expB():
    data = load("p6_results_expB.json")
    curves = data.get("curves", {})
    p6     = data.get("P6_tests", {})

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    fig.suptitle("Exp B: P6 — Larger Models Reach T* Earlier\n"
                 "(Qwen2.5-1.5B vs 3B, MATH-500)", fontsize=12)

    ax1, ax2 = axes
    model_cols = {"qwen_1b5": BLUE, "qwen_3b": RED}
    model_lbls = {"qwen_1b5": "Qwen2.5-1.5B", "qwen_3b": "Qwen2.5-3B"}

    for lv, lv_data in curves.items():
        if not isinstance(lv_data, dict):
            continue
        for mkey, series in lv_data.items():
            if not series or not isinstance(series, list):
                continue
            col = model_cols.get(mkey, PURPLE)
            budgets = [pt["budget"] for pt in series]
            accs    = [pt["accuracy"] * 100 for pt in series]
            lbl = f"{model_lbls.get(mkey, mkey)} ({LEVEL_LABELS.get(lv, lv)})"
            ax1.plot(budgets, accs, color=col, lw=2, marker="o", ms=4, label=lbl)

    ax1.set_xlabel("Budget T (tokens)", fontsize=10)
    ax1.set_ylabel("Accuracy (%)", fontsize=10)
    ax1.set_title("Accuracy curves by model size", fontsize=11)
    ax1.set_xscale("log")
    ax1.legend(fontsize=8)

    # P6 T* bar chart
    lv_keys = list(p6.keys())
    sizes_list = []; tstar_list = []; size_labels = []
    for lv in lv_keys:
        tstars = p6[lv].get("T_stars", {})
        params = p6[lv].get("param_Ms", {})
        for mkey in sorted(tstars.keys()):
            sizes_list.append(params.get(mkey, 0))
            tstar_list.append(tstars[mkey] / 1000)
            size_labels.append(model_lbls.get(mkey, mkey))

    x = np.arange(len(sizes_list))
    bars = ax2.bar(x, tstar_list,
                   color=[BLUE, RED][:len(sizes_list)], alpha=0.85, width=0.5)
    ax2.set_xticks(x)
    ax2.set_xticklabels(size_labels, fontsize=9)
    ax2.set_ylabel("$T^*$ (thousands of tokens)", fontsize=10)
    ax2.set_title(r"$T^*$ decreases with model size (P6 $\checkmark$)", fontsize=11)
    for bar, val in zip(bars, tstar_list):
        ax2.text(bar.get_x() + bar.get_width()/2, val + 0.05,
                 f"{val:.1f}K", ha="center", fontsize=9, fontweight="bold")
    mono = p6.get(lv_keys[0], {}).get("monotone_decreasing_with_N", None)
    ax2.set_title(r"$T^*$ vs. model size — monotone: " + str(mono), fontsize=11)

    fig.tight_layout()
    out = os.path.join(FIGS, "fig_expB_p6.png")
    fig.savefig(out, bbox_inches="tight", dpi=200)
    plt.close(fig)
    print(f"  saved → {out}")

    # Write LaTeX table
    tex = (
        "% Auto-generated by generate_tables.py from results/p6_results_expB.json\n"
        "\\begin{table}[t]\n"
        "\\centering\\small\n"
        "\\caption{Exp B (P6): Fitted $T^*$ by model size. "
        "Monotone-decreasing: \\textbf{True} ($\\partial T^*/\\partial N < 0$ at L1).}\n"
        "\\label{tab:expB_p6}\n"
        "\\begin{tabular}{lccc}\n"
        "\\toprule\n"
        "Model & Params (M) & $T^*$ (tokens) & $T^*$ monotone $\\downarrow$ \\\\\n"
        "\\midrule\n"
    )
    for lv in lv_keys:
        tstars = p6[lv].get("T_stars", {})
        params = p6[lv].get("param_Ms", {})
        mono   = p6[lv].get("monotone_decreasing_with_N", None)
        for i, mkey in enumerate(sorted(tstars.keys())):
            mono_str = "\\checkmark" if (i == len(tstars)-1 and mono) else ("--" if i < len(tstars)-1 else "\\texttimes")
            tex += (f"{model_lbls.get(mkey,mkey)} & {params.get(mkey,'--')} & "
                    f"{tstars[mkey]:.0f} & {mono_str} \\\\\n")
    tex += "\\bottomrule\n\\end{tabular}\n\\end{table}\n"
    with open(os.path.join(TABLES, "tab_expB_p6.tex"), "w") as f:
        f.write(tex)
    print("  saved → results/tab_expB_p6.tex")


# =============================================================================
# Exp D — Precision sweep (P3 test)
# =============================================================================
def process_expD():
    data  = load("precision_results_expD.json")
    p3    = data.get("P3_tests", {})

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    fig.suptitle("Exp D: T* by Precision and Difficulty (P3 test)\n"
                 "(Phi-3.5-mini, MATH-500)", fontsize=12)

    prec_order = ["fp16", "bf16", "int8", "int4"]
    prec_lbls  = {"fp16": "FP16", "bf16": "BF16", "int8": "INT8", "int4": "INT4"}
    lv_order   = ["Level_1", "Level_5"]
    lv_lbls    = {"Level_1": "L1 (easy)", "Level_5": "L5 (hard)"}

    for ax, lv in zip(axes, lv_order):
        if lv not in p3:
            ax.set_visible(False)
            continue
        lv_data  = p3[lv]
        tstars   = lv_data.get("T_stars", {})
        precs_av = lv_data.get("precisions_available", [])
        vals = [(p, tstars[p]/1000) for p in prec_order if p in tstars]
        if not vals:
            ax.set_visible(False)
            continue
        precs_plot, ts_plot = zip(*vals)
        cols = [PREC_COLORS[p] for p in precs_plot]
        bars = ax.bar(precs_plot, ts_plot, color=cols, alpha=0.85, width=0.5)
        for bar, val in zip(bars, ts_plot):
            ax.text(bar.get_x() + bar.get_width()/2, val + 0.05,
                    f"{val:.1f}K", ha="center", fontsize=9, fontweight="bold")
        mono = lv_data.get("monotone_decreasing", False)
        ax.set_title(f"{lv_lbls.get(lv, lv)} — monotone: {mono}", fontsize=11)
        ax.set_xlabel("Precision", fontsize=10)
        ax.set_ylabel("$T^*$ (thousands of tokens)", fontsize=10)
        ax.set_ylim(0, max(ts_plot) * 1.25)

    fig.tight_layout()
    out = os.path.join(FIGS, "fig_expD_precision.png")
    fig.savefig(out, bbox_inches="tight", dpi=200)
    plt.close(fig)
    print(f"  saved → {out}")

    # Write LaTeX table
    tex = (
        "% Auto-generated by generate_tables.py from results/precision_results_expD.json\n"
        "\\begin{table}[t]\n"
        "\\centering\\small\n"
        "\\caption{Exp D (P3): Fitted $T^*$ by numerical precision and difficulty. "
        "P3 predicts $T^*$ should decrease monotonically with lower precision; "
        "neither level shows strict monotonicity at small scale.}\n"
        "\\label{tab:expD_precision}\n"
        "\\begin{tabular}{lccccl}\n"
        "\\toprule\n"
        "Level & FP16 & BF16 & INT8 & INT4 & Monotone $\\downarrow$? \\\\\n"
        "\\midrule\n"
    )
    for lv in lv_order:
        if lv not in p3:
            continue
        tstars = p3[lv].get("T_stars", {})
        mono   = p3[lv].get("monotone_decreasing", False)
        vals   = " & ".join(
            f"{tstars[p]:.0f}" if p in tstars else "--"
            for p in prec_order
        )
        mono_str = "\\checkmark" if mono else "\\texttimes"
        tex += f"{lv_lbls.get(lv, lv)} & {vals} & {mono_str} \\\\\n"
    tex += "\\bottomrule\n\\end{tabular}\n\\end{table}\n"
    with open(os.path.join(TABLES, "tab_expD_precision.tex"), "w") as f:
        f.write(tex)
    print("  saved → results/tab_expD_precision.tex")


# Updated prediction-status table from real data
def write_prediction_status():
    a = load("multimodel_results_expA.json")
    b = load("p6_results_expB.json")
    c = load("hurst_results_expC.json")
    d = load("precision_results_expD.json")
    e = load("prospective_results_expE.json")

    # P1 evidence
    p1_qwen = a.get("P1_per_model", {}).get("qwen3b", {})
    p1_mono = p1_qwen.get("monotonic", False)
    p1_ratio = p1_qwen.get("ratio", None)
    p1_status = "Mixed" if not p1_mono else "Partial support"
    p1_note = (f"Qwen3B T*(L5)/T*(L1)={p1_ratio:.2f}; "
               "Phi-3.5 L1 ceiling (100\\%)" if p1_ratio else "Ceiling at L1; Qwen3B non-monotone")

    # P3 evidence
    p3_lv5 = d.get("P3_tests", {}).get("Level_5", {})
    p3_mono = p3_lv5.get("monotone_decreasing", False)
    p3_ts   = p3_lv5.get("T_stars", {})
    p3_note = (f"FP16={p3_ts.get('fp16',0):.0f}, INT8={p3_ts.get('int8',0):.0f}; "
               "non-monotone at L5")

    # P5 evidence
    ph_l3 = c.get("phi35", {}).get("Level_3", [])
    H_est  = "\\approx 0" if ph_l3 else "N/A"
    p5_note = "V(T) flat; $\\hat{H}\\approx 0$, not 0.5"

    # P6 evidence
    p6_lv1 = b.get("P6_tests", {}).get("Level_1", {})
    p6_mono = p6_lv1.get("monotone_decreasing_with_N", False)
    tstars  = p6_lv1.get("T_stars", {})
    p6_note = (f"Qwen1.5B T*={tstars.get('qwen_1b5',0):.0f} > "
               f"Qwen3B T*={tstars.get('qwen_3b',0):.0f} at L1 (\\checkmark)")

    tex = (
        "% Auto-generated by generate_tables.py — real experiment data\n"
        "\\begin{table}[t]\n"
        "\\centering\\small\n"
        "\\caption{Updated prediction-status table from Experiments A--E.\n"
        "  \\textbf{Mixed} = correct direction in subset; "
        "  \\textbf{Not supported} = controlled test gives opposite ordering;\n"
        "  \\textbf{Partial} = some conditions confirmed.}\n"
        "\\label{tab:prediction-status}\n"
        "\\begin{tabular}{lllp{6.5cm}}\n"
        "\\toprule\n"
        "Pred. & Status & Exp. & Key finding \\\\\n"
        "\\midrule\n"
        f"P1 & Mixed & Exp.~A & {p1_note} \\\\\n"
        f"P3 & Not supported & Exp.~D & {p3_note} \\\\\n"
        "P4 & Not confirmed & Exp.~A & Peak magnitudes do not follow $1/|\\Delta|$ at small scale \\\\\n"
        f"P5 & Not supported & Exp.~C & {p5_note} \\\\\n"
        f"P6 & Partial & Exp.~B & {p6_note} \\\\\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{table}\n"
    )
    with open(os.path.join(TABLES, "tab_prediction_status.tex"), "w") as f:
        f.write(tex)
    print("  saved → results/tab_prediction_status.tex")

    print("\n  === Prediction status (from real data) ===")
    rows = [
        ("P1", "Mixed",         "Exp A", p1_note),
        ("P3", "Not supported", "Exp D", p3_note),
        ("P4", "Not confirmed", "Exp A", "Peak magnitude test inconclusive at small scale"),
        ("P5", "Not supported", "Exp C", p5_note),
        ("P6", "Partial",       "Exp B", p6_note),
    ]
    for r in rows:
        print(f"  {r[0]:3s} | {r[1]:15s} | {r[2]:5s} | {r[3][:70]}")


# =============================================================================
# Main
# =============================================================================
if __name__ == "__main__":
    print("Generating tables\n")
    print("--- Exp A (P1: T* by difficulty) ---")
    process_expA()
    print("\n--- Exp B (P6: T* by model size) ---")
    process_expB()
    print("\n--- Exp D (P3: T* by precision) ---")
    process_expD()
    print("\n--- Prediction status table ---")
    write_prediction_status()
    print(f"\nAll outputs saved to {os.path.abspath(FIGS)} and {os.path.abspath(TABLES)}")
